export interface VirtualBackgroundPreset {
  id: string;
  name: string;
  category: "natural" | "curtains" | "strips" | "aesthetic" | "scenic" | "cyber" | "studio" | "custom";
  type: "none" | "blur" | "image" | "gradient" | "custom";
  thumbnail: string;
  imageUrl?: string;
  gradient?: string;
  color?: string;
  description: string;
}

export const VIRTUAL_BACKGROUNDS: VirtualBackgroundPreset[] = [
  {
    id: "none",
    name: "Original Camera",
    category: "natural",
    type: "none",
    thumbnail: "bg-zinc-800",
    description: "Keep your natural room background",
  },
  {
    id: "blur",
    name: "Studio Blur",
    category: "natural",
    type: "blur",
    thumbnail: "bg-gradient-to-tr from-zinc-700 to-zinc-900",
    description: "Soft cinematic portrait background blur",
  },
  {
    id: "cozy-curtain",
    name: "Classic Red Velvet",
    category: "curtains",
    type: "image",
    thumbnail: "bg-rose-950",
    imageUrl: "https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=1200&auto=format&fit=crop&q=80",
    description: "Iconic vintage photobooth velvet curtain",
  },
  {
    id: "pink-curtain",
    name: "Blush Silk Curtain",
    category: "curtains",
    type: "image",
    thumbnail: "bg-pink-950",
    imageUrl: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=1200&auto=format&fit=crop&q=80",
    description: "Soft romantic pink silk drapery",
  },
  {
    id: "gold-fringe-curtain",
    name: "Gold Shimmer Curtain",
    category: "curtains",
    type: "image",
    thumbnail: "bg-amber-900",
    imageUrl: "https://images.unsplash.com/photo-1533227268428-f9ed0900fb3b?w=1200&auto=format&fit=crop&q=80",
    description: "Glamorous gold metallic fringe curtain",
  },
  {
    id: "emerald-curtain",
    name: "Emerald Velvet Drape",
    category: "curtains",
    type: "image",
    thumbnail: "bg-emerald-950",
    imageUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1200&auto=format&fit=crop&q=80",
    description: "Rich dark emerald luxury theater drape",
  },
  {
    id: "purple-curtain",
    name: "Broadway Purple Curtain",
    category: "curtains",
    type: "image",
    thumbnail: "bg-purple-950",
    imageUrl: "https://images.unsplash.com/photo-1513151233558-d860c5398176?w=1200&auto=format&fit=crop&q=80",
    description: "Vibrant royal purple stage drape",
  },
  {
    id: "pastel-stripes",
    name: "Pastel Carnival Stripes",
    category: "strips",
    type: "image",
    thumbnail: "bg-pink-300",
    imageUrl: "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?w=1200&auto=format&fit=crop&q=80",
    description: "Cheerful pastel color stripe wallpaper",
  },
  {
    id: "retro-rainbow",
    name: "Vintage Rainbow Bars",
    category: "strips",
    type: "gradient",
    gradient: "linear-gradient(90deg, #ff4b72 0%, #ffa14a 20%, #ffd54a 40%, #38ef7d 60%, #11998e 80%, #667eea 100%)",
    thumbnail: "bg-gradient-to-r from-red-500 via-yellow-400 to-blue-500",
    description: "70s retro rainbow vertical color bars",
  },
  {
    id: "neon-wave-stripes",
    name: "Cyber Neon Strip Wave",
    category: "strips",
    type: "image",
    thumbnail: "bg-cyan-900",
    imageUrl: "https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=1200&auto=format&fit=crop&q=80",
    description: "Glowing neon stripes and abstract waves",
  },
  {
    id: "minimal-stripes",
    name: "Modernist Beige & Terracotta",
    category: "strips",
    type: "gradient",
    gradient: "linear-gradient(90deg, #fef3c7 0%, #fed7aa 25%, #fbcfe8 50%, #fed7aa 75%, #fef3c7 100%)",
    thumbnail: "bg-gradient-to-r from-amber-100 to-rose-200",
    description: "Warm architectural minimalist color bars",
  },
  {
    id: "tokyo-sakura",
    name: "Tokyo Cherry Blossom",
    category: "scenic",
    type: "image",
    thumbnail: "bg-pink-900",
    imageUrl: "https://images.unsplash.com/photo-1522383225653-ed111181a951?w=1200&auto=format&fit=crop&q=80",
    description: "Spring sakura blossoms in full bloom",
  },
  {
    id: "paris-sunset",
    name: "Parisian Sunset",
    category: "scenic",
    type: "image",
    thumbnail: "bg-amber-900",
    imageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=1200&auto=format&fit=crop&q=80",
    description: "Golden hour glow overlooking Paris rooftops",
  },
  {
    id: "bali-beach",
    name: "Bali Sunset Palms",
    category: "scenic",
    type: "image",
    thumbnail: "bg-orange-950",
    imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop&q=80",
    description: "Romantic tropical golden beach sunset",
  },
  {
    id: "neon-seoul",
    name: "Cyber Seoul Night",
    category: "cyber",
    type: "image",
    thumbnail: "bg-purple-950",
    imageUrl: "https://images.unsplash.com/photo-1546874177-9e664107314e?w=1200&auto=format&fit=crop&q=80",
    description: "Glowing neon reflections and cyber street lights",
  },
  {
    id: "dreamy-clouds",
    name: "Pastel Cloud 9",
    category: "aesthetic",
    type: "image",
    thumbnail: "bg-pink-950",
    imageUrl: "https://images.unsplash.com/photo-1534088568595-a066f410bcda?w=1200&auto=format&fit=crop&q=80",
    description: "Fluffy sunset clouds with dreamy pink hues",
  },
  {
    id: "starry-galaxy",
    name: "Celestial Galaxy Stars",
    category: "scenic",
    type: "image",
    thumbnail: "bg-indigo-950",
    imageUrl: "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?w=1200&auto=format&fit=crop&q=80",
    description: "Deep space nebula and cosmic stars",
  },
  {
    id: "vintage-diner",
    name: "Retro 80s Diner",
    category: "aesthetic",
    type: "image",
    thumbnail: "bg-cyan-950",
    imageUrl: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1200&auto=format&fit=crop&q=80",
    description: "Classic neon lighting and diner booth",
  },
  {
    id: "sparkle-bokeh",
    name: "Rose Gold Bokeh Lights",
    category: "aesthetic",
    type: "image",
    thumbnail: "bg-rose-900",
    imageUrl: "https://images.unsplash.com/photo-1519751138087-5bf79df62d5b?w=1200&auto=format&fit=crop&q=80",
    description: "Dreamy twinkling fairy lights and bokeh",
  },
  {
    id: "coffee-shop",
    name: "Cozy Aesthetic Cafe",
    category: "aesthetic",
    type: "image",
    thumbnail: "bg-amber-950",
    imageUrl: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=1200&auto=format&fit=crop&q=80",
    description: "Warm ambient lighting in a vintage coffee shop",
  },
  {
    id: "studio-white",
    name: "Clean Studio White",
    category: "studio",
    type: "gradient",
    gradient: "linear-gradient(180deg, #ffffff 0%, #f4f4f5 100%)",
    color: "#ffffff",
    thumbnail: "bg-white",
    description: "Bright pure studio portrait white",
  },
  {
    id: "studio-black",
    name: "Onyx Matte Dark",
    category: "studio",
    type: "gradient",
    gradient: "linear-gradient(180deg, #18181b 0%, #09090b 100%)",
    color: "#09090b",
    thumbnail: "bg-zinc-950",
    description: "Deep studio black with luxury contrast",
  },
  {
    id: "pastel-blush",
    name: "Pastel Sakura Studio",
    category: "studio",
    type: "gradient",
    gradient: "linear-gradient(135deg, #fdf2f8 0%, #fce7f3 50%, #fed7aa 100%)",
    thumbnail: "bg-gradient-to-tr from-pink-300 to-amber-200",
    description: "Minimalist soft pastel glow studio",
  },
  {
    id: "sunset-vibes",
    name: "Radiant Sunset Glow",
    category: "studio",
    type: "gradient",
    gradient: "linear-gradient(135deg, #fa709a 0%, #fee140 100%)",
    thumbnail: "bg-gradient-to-tr from-pink-500 to-yellow-400",
    description: "Vibrant warm pink to golden yellow gradient",
  },
  {
    id: "beige-arch",
    name: "Architectural Chic",
    category: "studio",
    type: "gradient",
    gradient: "linear-gradient(180deg, #fef3c7 0%, #fde68a 50%, #d97706 100%)",
    thumbnail: "bg-gradient-to-tr from-amber-200 to-amber-600",
    description: "Warm luxury beige gallery arch",
  },
  {
    id: "cyber-matrix",
    name: "Cyber Hologram",
    category: "cyber",
    type: "gradient",
    gradient: "radial-gradient(circle at center, #311042 0%, #0f172a 70%, #020617 100%)",
    thumbnail: "bg-gradient-to-tr from-purple-900 to-cyan-900",
    description: "Futuristic dark holographic matrix",
  },
  {
    id: "chroma-green",
    name: "Chroma Key Green",
    category: "studio",
    type: "gradient",
    gradient: "linear-gradient(180deg, #00ff00 0%, #00dd00 100%)",
    color: "#00ff00",
    thumbnail: "bg-green-500",
    description: "Standard production green screen",
  },
];

export function getVirtualBackground(id?: string, customUrl?: string): VirtualBackgroundPreset {
  if (id === "custom" && customUrl) {
    return {
      id: "custom",
      name: "Custom Uploaded Design",
      category: "custom",
      type: "image",
      thumbnail: "bg-pink-600",
      imageUrl: customUrl,
      description: "Your custom uploaded background image",
    };
  }
  if (!id) return VIRTUAL_BACKGROUNDS[0];
  return VIRTUAL_BACKGROUNDS.find((bg) => bg.id === id) || VIRTUAL_BACKGROUNDS[0];
}

